### PR TITLE
Add teletype (tt) tag to those that are converted to inline code.

### PR DESCRIPTION
**Pull request by stephenmcd**
The teletype tag is used to represent text with a fixed-width font. This change adds it to the tags that are converted to inline code.

### CODE REVIEW

**Comment by stephenmcd** [comment]
I've also moved the `__main__` code into a main() function that can be referenced as an entrypoint script. This means when installed, you can just run the command "html2text" system-wide. Sorry about not using separate branches.

**Comment by stephenmcd** [comment]
My use-case is piping unicode output from another program into html2text, however there's currently no way to provide an encoding when read from stdin. I've made utf-8 the default encoding.

**Comment by aaronsw** [comment]
Seems reasonable. Did you run the automated tests?

**Comment by stephenmcd** [comment]
Yep they all pass. What do you think about the encoding change for reading stdin? My first thought was to rearrange the options to make encoding a named option so that you could specify the encoding type when reading stdin, but that would mean changing the existing api.

**Comment by aaronsw** [comment]
Having utf8 as the default sounds right to me.

**Comment by stephenmcd** [comment]
Alright then. Thanks for the merge :-)

**Pull request merged**
