### PR TITLE
Add option to render emphasis with asterisks

### PR DESCRIPTION
**Pull request by ap**
I like them better.

### CODE REVIEW

**Comment by ap** [comment]
Any comments on this patch?

**Comment by aaronsw** [comment]
Sorry, ap -- not sure how I missed this. I'll merge it, but it'd be great if you added a test for it.

**Comment by ap** [comment]
I wanted to write a test but there aren’t any for any of the other switches either (at least as far as I could tell – did I miss them?), and I know next to nothing about the customs in Python. So I didn’t feel confident making up something and wondered if it’s even necessary. If you write any test for some other switch I can follow that structure and give you a test for this one no problem, though.

**Comment by aaronsw** [comment]
Yeah, the tests don't follow any sane convention, unfortunately. I just
messed around with them a bit and added one for your new option.

**Pull request merged**
