### PR TITLE
Best management HTML character entity

### PR DESCRIPTION
**Pull request by KanorUbu**
Hi
I have modify the program for to take into consideration the accents in HTML character entity.
Example :
 &agrave; → a in aarowsw/master
 &agrave; → à in KanorUbu/master

### CODE REVIEW

**Comment by aaronsw** [comment]
Have you tried just turning UNICODE_SNOB on?

**Comment by KanorUbu** [comment]
oh i have not see this feature. My pull request is useless. Thank you.

**Comment by aaronsw** [comment]
If you want to turn it on by default, now might be the time (it's been 12 years...).

**Comment by KanorUbu** [comment]
Good idea, unicode is standard now.

**Pull request closed without merging**
