### PR TITLE
Add python 3.3 to supported versions

### PR DESCRIPTION
**Pull request by saulshanabrook**
However maybe the untested versions should be removed, like 2.3, 2.4, and 3.0, 3.1

### CODE REVIEW

**Comment by mcepl** [comment]
Most likely obsoleted by #77, which seems to me to be more comprehensive.

**Comment by saulshanabrook** [comment]
It isn't, this only specifies python 3.3 as supported in the setup.py metadata, while the other pull request fixes python 3.x compatability

**Comment by mcepl** [comment]
I have added mcepl/html2text@cf01cfd to #77. Still not enough duplicity? ;)

**Comment by saulshanabrook** [comment]
Looks great :+1:

**Pull request closed without merging**
